# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src', 'src'),
        ('.env.example', '.'),
    ],
    hiddenimports=[
        'src.database',
        'src.logger',
        'src.ai_client',
        'src.syllabus_parser',
        'src.quiz_generator',
        'src.progress_dashboard',
        'src.goals_manager',
        'src.platform_integrator',
        'src.bookmark_manager',
        'src.study_session_manager',
        'src.spaced_repetition',
        'src.notes_generator',
        'src.video_analyzer',
        'src.resource_finder',
        'src.youtube_client',
        'src.achievement_system',
        'src.calendar_sync',
        'src.config',
        'src.content_recommender',
        'src.difficulty_analyzer',
        'src.export_system',
        'src.feedback_system',
        'src.leaderboard',
        'src.learning_analytics',
        'src.notification_system',
        'src.podcast_integrator',
        'textual',
        'rich',
        'youtube_transcript_api',
        'requests',
        'PyPDF2',
        'python_dotenv',
        'beautifulsoup4',
        'lxml',
        'feedparser',
        'googleapiclient',
        'google.generativeai',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='syllabo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)